; Endpoints generated by prelude.c
declare void @__c_print_int(i32)
declare void @__c_println_int(i32)
declare void @__c_print_str(ptr)
declare void @__c_println_str(ptr)
declare i32 @__c_get_int()
declare i32 @__c_strlen(ptr)

; Bind to prelude functions
define void @prelude.func.print(ptr %0) {
entry:
    call void @__c_print_str(ptr %0)
    ret void
}
define void @prelude.func.println(ptr %0) {
    call void @__c_println_str(ptr %0)
    ret void
}
define void @prelude.func.printInt(i32 %0) {
    call void @__c_print_int(i32 %0)
    ret void
}
define void @prelude.func.printlnInt(i32 %0) {
    call void @__c_println_int(i32 %0)
    ret void
}
define i32 @prelude.func.getInt() {
    %1 = call i32 @__c_get_int()
    ret i32 %1
}